# Generated by Django 2.2.3 on 2019-07-26 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('token', models.CharField(max_length=255, null=True, unique=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='token_user', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('value', models.IntegerField()),
                ('user1', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='self', to='blog.User')),
                ('user2', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='other', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('content', models.TextField()),
                ('attach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attach_to_post', to='blog.Post')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='post_user_id', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photo/')),
                ('is_sticker', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('post', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_post_id', to='blog.Post')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='photo_user_id', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('text', models.TextField(null=True)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reciever', to='blog.User')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='like_post_id', to='blog.Post')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='like_user_id', to='blog.User')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('channel_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='client_user_id', to='blog.User')),
            ],
        ),
    ]
