# Generated by Django 2.2.3 on 2019-07-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('relationship_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('value', models.IntegerField()),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='self', to='blog.User')),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='other', to='blog.User')),
            ],
        ),
    ]
