# Generated by Django 2.2.3 on 2019-07-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190726_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uuu',
            new_name='user',
        ),
    ]
