# Generated by Django 2.2.3 on 2019-07-27 10:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190726_1224'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likepost',
            managers=[
                ('postlikes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('blogPhoto', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('mainPost', django.db.models.manager.Manager()),
            ],
        ),
    ]
