# Generated by Django 2.2.3 on 2019-07-17 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190717_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token',
        ),
    ]
