# Generated by Django 2.2.3 on 2019-07-27 10:46

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190727_1045'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='likepost',
            managers=[
                ('postLikes', django.db.models.manager.Manager()),
            ],
        ),
    ]
