# Generated by Django 2.2.3 on 2019-07-27 11:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190727_1046'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('userChat', django.db.models.manager.Manager()),
            ],
        ),
    ]
