# Generated by Django 2.2.3 on 2019-08-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190729_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('category', models.CharField(max_length=50, unique=True)),
                ('message', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='message_notify', to='blog.Message')),
                ('post', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='post_notify', to='blog.Post')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='user_notify', to='blog.User')),
            ],
        ),
    ]
