# Generated by Django 2.2.3 on 2019-07-17 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190717_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='token_user_id', to='blog.User'),
        ),
    ]
