# Generated by Django 2.2.3 on 2019-07-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikePost',
            fields=[
                ('likePost_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like_post_id', to='blog.Post')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='like_user_id', to='blog.User')),
            ],
        ),
    ]
