# Generated by Django 2.2.3 on 2019-07-18 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attach',
        ),
    ]
