# Generated by Django 2.2.3 on 2019-07-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_attach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('channel_name', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='client_user_id', to='blog.User')),
            ],
        ),
    ]
