# Generated by Django 2.2.3 on 2019-07-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_likepost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likepost',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
