# Generated by Django 2.2.3 on 2019-07-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='photo/')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Datetime')),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='photo_user_id', to='blog.User')),
            ],
        ),
    ]
