# Generated by Django 2.2.3 on 2019-07-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bbb', to='blog.Post'),
        ),
    ]
