# Generated by Django 2.2.3 on 2019-07-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190720_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='post_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo_post_id', to='blog.Post'),
        ),
    ]
